apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-4b-mig
  labels:
    app: mig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mig
  template:
    metadata:
      labels:
        app: mig
      annotations:
        nvidia.com/vgpu-mode: "mig"
    spec:
      containers:
        - image: vllm/vllm-openai:latest
          imagePullPolicy: IfNotPresent
          name: qwen3-4b-mig
          env:
            - name: LIBCUDA_LOG_LEVEL
              value: "2"
            - name: GPU_CORE_UTILIZATION_POLICY
              value: force
          command:
            - vllm
            - serve
            - Qwen/Qwen3-4B
            - --dtype=auto
            - --max-model-len=512
            - --enforce-eager
          resources:
            limits:
              nvidia.com/gpu: "1"
              nvidia.com/gpucores: "30"
              nvidia.com/gpumem: "10240"
