repositories:
  - name: hami-charts
    url: https://project-hami.github.io/HAMi

releases:
  - name: hami-core
    namespace: kube-system
    chart: hami-charts/hami
    version: "2.9.0"
    values:
      - scheduler:
          kubeScheduler:
            imageTag: "v1.35.3"
    labels:
      component: hami-core
      tag: hami
