apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen7b-service
  labels:
    app: qwen7b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen7b
  template:
    metadata:
      labels:
        app: qwen7b
      annotations:
        hami.io/node-scheduler-policy: binpack
        hami.io/gpu-scheduler-policy: binpack
    spec:
      schedulerName: hami-scheduler
      containers:
        - name: vllm-qwen7b
          image: vllm/vllm-openai:latest
          command:
            [
              "vllm",
              "serve",
              "Qwen/Qwen3-8B",
              "--max-model-len=8192",
              "--gpu-memory-utilization=0.9",
              "--host",
              "0.0.0.0",
            ]
          resources:
            limits:
              nvidia.com/gpu: "1"
              nvidia.com/gpucores: "30"
              nvidia.com/gpumem: "25000"
---
apiVersion: v1
kind: Service
metadata:
  name: qwen7b-service
spec:
  selector:
    app: qwen7b
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
